name: Release File Storage
 
on:
  push:
    tags:
      - "file*"
  workflow_dispatch:

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm i -g pnpm
      - run: pnpm install 
      - run: pnpm run build -- --scope=@satont/grammy-file-storage
      - run: pnpm run test -- --scope=@satont/grammy-file-storage
      - run: pnpm publish --filter=@satont/grammy-file-storage --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  publish-nest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Deno
        uses: maximousblk/setup-deno@v1
      - run: deno -V
      - name: Run tests
        run: deno test packages/file/__tests__/deno.ts --allow-write --no-check --allow-read --unstable
      - name: Publish
        run: |
          deno install -Af --unstable https://x.nest.land/eggs@0.3.10/eggs.ts
          eggs link ${{ secrets.NESTAPIKEY }}
          deno run --allow-read --allow-net --allow-env --unstable eggs.ts file