name: Tests File Storage

on:
  push:
    paths:
      - packages/file/**
  workflow_dispatch:

jobs:
  node-tests:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i -g pnpm
      - name: install dependencies
        run: pnpm install 
      - name: build
        run: pnpm run build -- --scope=@grammyjs/grammy-file-storage
      - name: tests
        run: pnpm run test -- --scope=@grammyjs/grammy-file-storage
  deno-tests:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Deno
        uses: maximousblk/setup-deno@v1
      - run: deno -V
      - name: Run tests
        run: deno test packages/file/__tests__/deno.ts --allow-write --no-check --allow-read --unstable